---
title: "Module 7 Project"
author: "Group 7"
date: "2023-10-30"
output: html_document
bibliography: BIOL3140.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)

data <- readRDS("proj7_data.rds")
```

# Introduction
The amount of force produced by muscle tissue is dependent on the relationship between the speed of contraction and the length of the muscle, but this project focuses specifically on the force-length relationship. 

# Methods
To obtain force data, a set-up consisting of a 100-kg S-type Load Cell with HX711 amplifier and an Arduino Uno microcontroller was constructed. Using an Arduino sketch to obtain data, individuals performed isometric contractions at different angles when grabbing the handle of the Load Cell. The different angles ranged from 45° to 157.5° at 11.25° intervals, with a ganiometer being strapped to the arm at the elbow joint to see what angle the arm was making for each contraction.

# Results


# Discussion

# Author Contributions
Audrey: Methods
Ava:
Blake:
Conor: